config/routes.rb
Rails.application.routes.draw do


  devise_for :students, :controllers => {registrations: "students/registrations"}
  devise_for :teachers, :controllers => {registrations: "teachers/registrations"}
  resources :tests
  resources :scores

  get "test/finish" => "tests#finish", as: "finish"
  post "/guess" => "scores#guess", as: "guess"
  get 'welcome/index'
  get 'about/show'
  get 'about/index'
  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :student
  belongs_to :test
end

app/models/student.rb
class Student < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :scores
         has_many :tests, through: :scores
end

app/models/teacher.rb
class Teacher < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         has_many :tests
end

app/models/test.rb
class Test < ApplicationRecord
  belongs_to :teacher
  has_many :scores
  has_many :students, through: :scores
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

    def after_sign_in_path_for(resource)
       "/welcome/index"
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/scores_controller.rb
class ScoresController < ApplicationController
  def index
      @scores = Score.all

  end

  def show
      @score = Score.find(params[:id])
  end

  def guess
    puts 'this is the test id'
    puts params[:test_id]
  s = Score.new(score_params)
  if(params[:answer] == params[:correct_answer])
    s.result = "Answer: Correct"
  else
    s.result = 'Answer: Incorrect'
  end
  s.test_id = params[:test_id]
  s.student_id = current_student.id
  if s.save
    redirect_to "/scores"
  else
    render test_path(params[:test_id])
  end
end

  private

  def score_params
    params.permit(:result, :student_id, :test_id)
  end
end

app/controllers/students/passwords_controller.rb
# frozen_string_literal: true

class Students::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/students/sessions_controller.rb
# frozen_string_literal: true

class Students::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/students/unlocks_controller.rb
# frozen_string_literal: true

class Students::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/teachers/sessions_controller.rb
# frozen_string_literal: true

class Teachers::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/teachers/unlocks_controller.rb
# frozen_string_literal: true

class Teachers::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/tests_controller.rb
class TestsController < ApplicationController
  def index
    @tests = Test.all
  end

  def new
    @test = Test.new
  end

  def create
    test = Test.new(test_params)
    test.teacher_id = current_teacher.id
    if test.save
    redirect_to "/welcome/index"
    flash[:success] = "test has been created"
    else
    render "/tests/new"
    flash[:error] = "try again"
    end
  end

  def show
    @test = Test.find(params[:id])
  end


  def edit
    @test = Test.find(params[:id])
  end

  def update
    @test = Test.find(params[:id])
    if @test.save
      redirect_to
    else
      render test_edit_path
    end
  end

  def finish
    @finish = "finish"
  end

  def destroy
  test = Test.find(params[:id])
  test.destroy
  redirect_to "/welcome/index"
  end

  private

  def test_params
    params.require(:test).permit(:subject, :grade_level, :teacher_name, :teacher_id,
      :question, :answer1, :answer2, :answer3, :answer4, :correct_answer)
  end

  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/tests_helper.rb
module TestsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/about/index.html.erb
<h1>About Page</h1>

<div class="holdMission">
<div class="mission">
<h2><u>Mission and Vision</u></h2>

<h4><b>Our Vision Statement</b></h4>
<p>To encourage and promote continuous social and academic growth.</p>

<h4><b>Mission Statement for Educators</b></h4>
<p>In partnership with staff, students, family and community, to continually improve programs,
  services, and the performance of <br>
  students, staff, and administration.</p>

<h4><b>Mission Statement for  School</b></h4>
<p>The mission is for all students, staff, and families to work together to continually improve academic performance and citizenship.</p>
</div>
</div>

<br><%= link_to "Inspiration", about_show_path %>
<br><%= link_to "Home", root_path %>

app/views/about/show.html.erb
<h1>Motivational Quotes</h1>

<div class="pics">
<%= image_tag("qoute2.jpg", :size => '265x125') %>
<%= image_tag("qoute3.gif", :size => '265x125') %>
<%= image_tag("qoute4.jpg", :size => '265x125') %>
<%= image_tag("qoute5.jpg", :size => '265x125') %>
</div>
<br>
<br><%= link_to "Back", about_index_path %>

app/views/home/index.html.erb
<h1>Home Page</h1>
<p>Welcome to this website!</p>
<div class="holder">
<div class="qoute"><%= image_tag("quote1.png", :size => '610x250') %></div>
</div>
<div class="box"><div class="hands"><%= image_tag("raising_hands.jpg", :size => '610x250') %></div><p class="script">Ready to help students reach their full potential?</p></div>

app/views/welcome/index.html.erb
<% if current_teacher%>
  <h1>Welcome Teacher:  <%= current_teacher.user_name %></h1>
  <p>Don't forget to Logout when you have finished</p>
  <div class="intro">
    <div class="introPart">
  <h3>Instructions: </h3>
  <p> - To create an online test, select: Create Test<br><br>
      - To view the online test that was created, select: Test Link<br><br>
      - To view your students results after they have completed the online test, select: Student Results
   </p>
    </div>
  </div>
<br><a href="/tests/new">Create Test</a>
<%= link_to "Test Link", tests_path %>
<%= link_to "Student Results", scores_path %>
<% end %>

<% if current_student %>
  <h1>Welcome  Student: <%= current_student.user_name %></h1>
  <p>Don't forget to Logout when you have finished</p>
  <div class="introStudent">
    <div class="introPartStudent">
  <p>Click the link below to take you to your test page</p>
  </div>
</div>
  <br><%= link_to "Link", tests_path %>
<% end %>